kind: pipeline  
name: deploy  
  
steps:  
  - name: build  
    image: node:10  
    volumes:
      - name: code
        path: /code
    commands:  
      - echo $(pwd)
      - echo "hello1" >> tmp.log
      - cp tmp.log /code/
    when:  
      branch: master  
      event: push  

  - name: build_b  
    image: node:10  
    commands:  
      - echo $(pwd) >> tmp2.log
      - cp tmp2.log /code/
    volumes:
      - name: code
        path: /code
volumes:
  - name: code
    host:
      path: /drone