kind: pipeline  
name: deploy  
  
steps:  
  - name: build  
    image: node:10  
    volumes:
      - name: code
        path: /code
    commands:  
      - echo $DRONE_SERVER_HOST >> tmp.log
      - cp $DRONE_SERVER_HOST
      - cp ./ /code/
    when:  
      branch: master  
      event: push  

  - name: build_b  
    image: node:10  
    commands:  
      - echo $DRONE_ZHACAI_PATH
      - echo $DRONE_ZHACAI_PATH >> tmp2.log
      - cp tmp2.log /code/
    volumes:
      - name: code
        path: /code
volumes:
  - name: code
    host:
      path: /data