kind: pipeline  
name: deploy  
  
steps:  
  - name: build  
    image: node:10  
    commands:  
      - node -v
      - echo $(node -v) >> node.log
    when:  
      branch: master  
      event: push  

  - name: deploy  
    image: node:10  
    commands:  
      - cp -rf server/* /code/seed/server/
      - cp -rf client/* /code/seed/client/
    volumes:
      - name: deploy_path
        path: /code

volumes:
  - name: deploy_path
    host:
      path: /root/xhacai/xcloud/console/env/deploy/ci