kind: pipeline  
name: deploy  
  
steps:  
  - name: build  
    image: node:10  
    commands:  
      - node -v
    when:  
      branch: master  
      event: push  

  - name: deploy  
    image: node:10  
    commands:  
      - mkdir -p /deploy_path/seed/server_tmp
      - cp -rf * /deploy_path/seed/server_tmp/
      - rm -rf /deploy_path/seed/server
      - mv /deploy_path/seed/server_tmp /deploy_path/seed/server
    volumes:
      - name: code
        path: /code
        
volumes:
  - name: deploy_path
    host:
      path: /root/xhacai/xcloud/console/env/deploy/ci/drone/