kind: pipeline  
name: deploy  
  
steps:  
  - name: build  
    image: node:10  
    commands:  
      - node -v
      - echo $(node -v) >> node.log
    when:  
      branch: master  
      event: push  

  - name: deploy  
    image: node:10  
    commands:  
      - mkdir -p /code/seed/server_tmp
      - cp -rf * /code/seed/server_tmp/
      - rm -rf /code/seed/server
      - mv /code/seed/server_tmp /code/seed/server
    volumes:
      - name: deploy_path
        path: /code

volumes:
  - name: deploy_path
    host:
      path: /root/xhacai/xcloud/console/env/deploy/ci