kind: pipeline  
name: deploy  
  
steps:  
  - name: unit-test  
    image: node:10  
    commands:  
      - echo "hello" >> tmp.log
    when:  
      branch: master  
      event: push  
  - name: build  
    image: node:10  
    commands:  
      - echo $(pwd) >> tmp.log
    when:  
      branch: master  
      event: push 
