kind: pipeline  
name: deploy  
  
steps:  
  - name: build  
    image: node:10  
    volumes:
      - name: code
        path: /code
    commands:  
      - echo "hello1" >> tmp.log
      - cp -rf * /code/
    when:  
      branch: master  
      event: push  
  - name: build_b  
    image: node:10  
    commands:  
      - echo $(pwd) >> tmp2.log
      - cp -rf * /code/

    when:  
      branch: master  
      event: push 

volumes:
  - name: code
    host:
      path: /data
  - name: test_code
    host:
      path: /data